version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - github.com/dsha256/packer
            - github.com/goccy/go-json
            - gopkg.in/yaml.v3
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
          deny:
            - pkg: encoding/json
              desc: Use faster version github.com/goccy/go-json
    errcheck:
      check-type-assertions: true
      check-blank: true
    errchkjson:
      report-no-exported: true
    funlen:
      lines: 200
      statements: 100
      ignore-comments: true
    govet:
      enable-all: true
    lll:
      line-length: 200
      tab-width: 1
    mnd:
      checks:
        - return
    nolintlint:
      require-explanation: true
      require-specific: true
    varnamelen:
      min-name-length: 2
      check-receiver: true
      check-return: true
      ignore-names:
        - w # common for http.ResponseWriter
        - r # common for *http.Request
        - s # common for service
        - h # common for handler
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
      - linters:
          - revive
        path: internal/types/
        text: "var-naming: avoid meaningless package names"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
